#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
生成仿宋_GB2312字体的GFX格式文件
字符: 测试文字ABC123
"""

from PIL import Image, ImageDraw, ImageFont
import os

# 配置
TTF_PATH = r"G:\A_BL_Project\inkScree_fuben\仿宋_GB2312.ttf"  # 修改为你的字体路径
CHARS = "测试文字ABC123"
FONT_SIZE = 16
OUTPUT_NAME = "fangsong_GB2312"

def generate_gfx_font():
    """生成 GFX 格式字体"""
    if not os.path.exists(TTF_PATH):
        print(f"❌ 字体文件不存在: {TTF_PATH}")
        print("请将仿宋_GB2312.ttf放到项目根目录，或修改 TTF_PATH 变量")
        return
    
    try:
        font = ImageFont.truetype(TTF_PATH, FONT_SIZE)
    except Exception as e:
        print(f"❌ 加载字体失败: {e}")
        return
    
    bitmaps = []
    glyphs = []
    
    # 为每个字符生成位图
    for char in CHARS:
        # 获取字符边界
        bbox = font.getbbox(char)
        width = bbox[2] - bbox[0]
        height = bbox[3] - bbox[1]
        
        if width == 0 or height == 0:
            print(f"⚠️ 字符 '{char}' 尺寸为0，跳过")
            continue
        
        # 创建图像
        img = Image.new('1', (width, height), 1)
        draw = ImageDraw.Draw(img)
        draw.text((-bbox[0], -bbox[1]), char, font=font, fill=0)
        
        # 转换为字节数组
        pixels = list(img.getdata())
        bitmap_bytes = []
        
        for y in range(height):
            for x in range(0, width, 8):
                byte = 0
                for bit in range(8):
                    if x + bit < width:
                        if pixels[y * width + x + bit] == 0:
                            byte |= (0x80 >> bit)
                bitmap_bytes.append(byte)
        
        bitmaps.extend(bitmap_bytes)
        
        # 生成 Glyph 信息
        glyphs.append({
            'char': char,
            'bitmap_offset': len(bitmaps) - len(bitmap_bytes),
            'width': width,
            'height': height,
            'x_advance': width + 1,
            'x_offset': bbox[0],
            'y_offset': -bbox[3]
        })
    
    # 生成 .h 文件
    h_content = f"""// Font: {OUTPUT_NAME} {FONT_SIZE}pt
// Generated by convert_fangsong.py
// Characters: {CHARS}

#ifndef _{OUTPUT_NAME.upper()}_{FONT_SIZE}PT_H_
#define _{OUTPUT_NAME.upper()}_{FONT_SIZE}PT_H_

#include <Adafruit_GFX.h>

const uint8_t {OUTPUT_NAME}{FONT_SIZE}ptBitmaps[] PROGMEM = {{
"""
    
    # 位图数据
    for i, byte in enumerate(bitmaps):
        if i % 16 == 0:
            h_content += "    "
        h_content += f"0x{byte:02X}"
        if i < len(bitmaps) - 1:
            h_content += ", "
        if (i + 1) % 16 == 0:
            h_content += "\n"
    
    h_content += "\n};\n\n"
    
    # Glyphs 数据
    h_content += f"const GFXglyph {OUTPUT_NAME}{FONT_SIZE}ptGlyphs[] PROGMEM = {{\n"
    
    for g in glyphs:
        h_content += f"    {{ {g['bitmap_offset']:5d}, {g['width']:3d}, {g['height']:3d}, "
        h_content += f"{g['x_advance']:3d}, {g['x_offset']:4d}, {g['y_offset']:4d} }}"
        h_content += f"  // '{g['char']}'\n"
    
    h_content += "};\n\n"
    
    # Font 结构
    first_char = ord(CHARS[0])
    last_char = ord(CHARS[-1])
    
    h_content += f"""const GFXfont {OUTPUT_NAME}{FONT_SIZE}pt PROGMEM = {{
    (uint8_t *){OUTPUT_NAME}{FONT_SIZE}ptBitmaps,
    (GFXglyph *){OUTPUT_NAME}{FONT_SIZE}ptGlyphs,
    0x{first_char:04X}, 0x{last_char:04X}, {FONT_SIZE}
}};

#endif // _{OUTPUT_NAME.upper()}_{FONT_SIZE}PT_H_
"""
    
    # 保存文件
    output_path = f"components/fonts/{OUTPUT_NAME}{FONT_SIZE}pt7b.h"
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(h_content)
    
    print(f"✅ 转换成功！")
    print(f"📁 输出文件: {output_path}")
    print(f"📊 字符数: {len(glyphs)}")
    print(f"📊 位图大小: {len(bitmaps)} bytes")
    print(f"\n使用方法:")
    print(f"  #include \"../fonts/{OUTPUT_NAME}{FONT_SIZE}pt7b.h\"")

if __name__ == "__main__":
    generate_gfx_font()
