#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
生成独立的中文字符位图（每个字符一个数组）
避免 GFX 字体的 Unicode 范围问题
"""

from PIL import Image, ImageDraw, ImageFont
import os

# 配置
TTF_PATH = "components/fonts/仿宋_GB2312.ttf"
CHARS = "测试文字"  # 只转换中文
FONT_SIZE = 16
OUTPUT_NAME = "fangsong_bitmaps"

def generate_bitmap_arrays():
    """为每个字符生成独立的位图数组"""
    
    print("🔄 正在生成独立位图数组...")
    print(f"📁 字体: {TTF_PATH}")
    print(f"📝 字符: {CHARS}")
    print()
    
    if not os.path.exists(TTF_PATH):
        print(f"❌ 字体文件不存在")
        return
    
    try:
        font = ImageFont.truetype(TTF_PATH, FONT_SIZE)
        print("✅ 字体加载成功")
    except Exception as e:
        print(f"❌ 加载失败: {e}")
        return
    
    h_content = f"""// Font Bitmaps: {OUTPUT_NAME} {FONT_SIZE}pt
// Generated by generate_bitmap_arrays.py
// Characters: {CHARS}
// 每个字符一个独立的位图数组

#ifndef _{OUTPUT_NAME.upper()}_{FONT_SIZE}PT_H_
#define _{OUTPUT_NAME.upper()}_{FONT_SIZE}PT_H_

#include <Arduino.h>

"""
    
    char_info = []
    
    for char in CHARS:
        bbox = font.getbbox(char)
        width = bbox[2] - bbox[0]
        height = bbox[3] - bbox[1]
        
        if width <= 0 or height <= 0:
            print(f"⚠️  '{char}' 尺寸为0，跳过")
            continue
        
        # 创建图像
        img = Image.new('1', (width, height), 1)
        draw = ImageDraw.Draw(img)
        draw.text((-bbox[0], -bbox[1]), char, font=font, fill=0)
        
        # 转换为字节数组
        pixels = list(img.getdata())
        bitmap_bytes = []
        
        for y in range(height):
            for x in range(0, width, 8):
                byte = 0
                for bit in range(8):
                    if x + bit < width:
                        if pixels[y * width + x + bit] == 0:
                            byte |= (0x80 >> bit)
                bitmap_bytes.append(byte)
        
        # 生成数组名（使用 Unicode 码点）
        array_name = f"BITMAP_{ord(char):04X}"
        
        # 写入数组定义
        h_content += f"// '{char}' (U+{ord(char):04X}) - {width}x{height}\n"
        h_content += f"const uint8_t {array_name}[] PROGMEM = {{\n"
        h_content += "    "
        
        for i, byte in enumerate(bitmap_bytes):
            h_content += f"0x{byte:02X}"
            if i < len(bitmap_bytes) - 1:
                h_content += ", "
            if (i + 1) % 16 == 0 and i < len(bitmap_bytes) - 1:
                h_content += "\n    "
        
        h_content += "\n};\n\n"
        
        char_info.append({
            'char': char,
            'unicode': ord(char),
            'width': width,
            'height': height,
            'array_name': array_name,
            'size': len(bitmap_bytes)
        })
        
        print(f"✓ '{char}' (U+{ord(char):04X}): {width}x{height}, {len(bitmap_bytes)} bytes -> {array_name}")
    
    # 生成绘制函数
    h_content += f"""// 绘制函数模板（支持任意 GxEPD2 显示器类型）
template<typename T>
inline void draw{OUTPUT_NAME.title().replace('_', '')}(T& display, int16_t x, int16_t y, uint16_t scale = 1) {{
"""
    
    x_offset = 0
    for info in char_info:
        h_content += f"    // '{info['char']}'\n"
        h_content += f"    for (uint16_t s_y = 0; s_y < {info['height']} * scale; s_y++) {{\n"
        h_content += f"        for (uint16_t s_x = 0; s_x < {info['width']} * scale; s_x++) {{\n"
        h_content += f"            uint16_t src_x = s_x / scale;\n"
        h_content += f"            uint16_t src_y = s_y / scale;\n"
        h_content += f"            uint16_t byte_index = src_y * (({info['width']} + 7) / 8) + src_x / 8;\n"
        h_content += f"            uint8_t bit_mask = 0x80 >> (src_x % 8);\n"
        h_content += f"            if (pgm_read_byte(&{info['array_name']}[byte_index]) & bit_mask) {{\n"
        h_content += f"                display.drawPixel(x + {x_offset} * scale + s_x, y + s_y, GxEPD_BLACK);\n"
        h_content += f"            }}\n"
        h_content += f"        }}\n"
        h_content += f"    }}\n\n"
        x_offset += info['width'] + 1  # 字符间距
    
    h_content += "}\n\n"
    
    h_content += f"#endif // _{OUTPUT_NAME.upper()}_{FONT_SIZE}PT_H_\n"
    
    # 保存文件
    output_path = f"components/fonts/{OUTPUT_NAME}{FONT_SIZE}pt.h"
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(h_content)
    
    print()
    print(f"✅ 生成成功: {output_path}")
    print()
    print("=" * 60)
    print("使用方法:")
    print("=" * 60)
    print(f"#include \"../fonts/{OUTPUT_NAME}{FONT_SIZE}pt.h\"")
    print(f"drawFangsongBitmaps(display, 10, 50, 2);  // x, y, scale")
    print("=" * 60)

if __name__ == "__main__":
    generate_bitmap_arrays()
