#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
生成 "生成字库" 独立位图（高质量 Python 版本）
避免浏览器 Canvas 渲染质量不足的问题
"""

from PIL import Image, ImageDraw, ImageFont
import os
import sys

# 获取项目根目录
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)

# 配置
TTF_PATH = os.path.join(PROJECT_ROOT, "components", "fonts", "仿宋_GB2312.ttf")
CHARS = "生成字库"  # 要转换的字符
FONT_SIZE = 16
OUTPUT_NAME = "fangsong_shengcheng"

def generate_bitmap_arrays():
    """为每个字符生成独立的位图数组"""
    
    print("🔄 正在生成独立位图数组...")
    print(f"📁 字体: {TTF_PATH}")
    print(f"📝 字符: {CHARS}")
    print(f"📏 字号: {FONT_SIZE}pt")
    print()
    
    if not os.path.exists(TTF_PATH):
        print(f"❌ 字体文件不存在: {TTF_PATH}")
        return
    
    try:
        font = ImageFont.truetype(TTF_PATH, FONT_SIZE)
        print("✅ 字体加载成功")
    except Exception as e:
        print(f"❌ 加载失败: {e}")
        return
    
    h_content = f"""// Font Bitmaps: {OUTPUT_NAME} {FONT_SIZE}pt
// Generated by generate_shengcheng_ziku.py (Python + Pillow)
// Characters: {CHARS}
// 每个字符一个独立的位图数组（高质量渲染）

#ifndef _{OUTPUT_NAME.upper()}_{FONT_SIZE}PT_H_
#define _{OUTPUT_NAME.upper()}_{FONT_SIZE}PT_H_

#include <Arduino.h>

"""
    
    char_info = []
    
    for char in CHARS:
        bbox = font.getbbox(char)
        width = bbox[2] - bbox[0]
        height = bbox[3] - bbox[1]
        
        if width <= 0 or height <= 0:
            print(f"⚠️  '{char}' 尺寸为0，跳过")
            continue
        
        # 创建图像
        img = Image.new('1', (width, height), 1)
        draw = ImageDraw.Draw(img)
        draw.text((-bbox[0], -bbox[1]), char, font=font, fill=0)
        
        # 转换为字节数组
        pixels = list(img.getdata())
        bitmap_bytes = []
        
        for y in range(height):
            for x in range(0, width, 8):
                byte = 0
                for bit in range(8):
                    if x + bit < width:
                        if pixels[y * width + x + bit] == 0:
                            byte |= (0x80 >> bit)
                bitmap_bytes.append(byte)
        
        # 生成数组名（使用 Unicode 码点）
        array_name = f"BITMAP_{ord(char):04X}"
        
        # 写入数组定义
        h_content += f"// '{char}' (U+{ord(char):04X}) - {width}x{height}\n"
        h_content += f"const uint8_t {array_name}[] PROGMEM = {{\n"
        h_content += "    "
        
        for i, byte in enumerate(bitmap_bytes):
            h_content += f"0x{byte:02X}"
            if i < len(bitmap_bytes) - 1:
                h_content += ", "
            if (i + 1) % 16 == 0 and i < len(bitmap_bytes) - 1:
                h_content += "\n    "
        
        h_content += "\n};\n\n"
        
        char_info.append({
            'char': char,
            'unicode': ord(char),
            'width': width,
            'height': height,
            'array_name': array_name,
            'size': len(bitmap_bytes)
        })
        
        print(f"✓ '{char}' (U+{ord(char):04X}): {width}x{height}, {len(bitmap_bytes)} bytes -> {array_name}")
    
    # 生成单字符绘制函数
    h_content += f"""// 绘制单个字符
template<typename T>
void draw{OUTPUT_NAME.title().replace('_', '')}Char(T& display, int16_t x, int16_t y, uint16_t charCode) {{
    const uint8_t* bitmap = nullptr;
    uint8_t width = 0, height = {FONT_SIZE};

    switch(charCode) {{
"""
    
    for info in char_info:
        h_content += f"        case 0x{info['unicode']:04X}: bitmap = {info['array_name']}; width = {info['width']}; height = {info['height']}; break;\n"
    
    h_content += """        default: return; // 未知字符
    }

    if (bitmap) {
        display.drawBitmap(x, y, bitmap, width, height, GxEPD_BLACK);
    }
}

// 绘制 UTF-8 字符串
template<typename T>
void draw"""
    
    h_content += f"""{OUTPUT_NAME.title().replace('_', '')}String(T& display, int16_t x, int16_t y, const char* text) {{
    int16_t currentX = x;
    const uint8_t* p = (const uint8_t*)text;

    while (*p) {{
        uint16_t charCode = 0;
        // UTF-8 解码
        if ((*p & 0x80) == 0) {{  // 1字节 ASCII
            charCode = *p++;
        }} else if ((*p & 0xE0) == 0xC0) {{  // 2字节
            charCode = ((*p++ & 0x1F) << 6);
            charCode |= (*p++ & 0x3F);
        }} else if ((*p & 0xF0) == 0xE0) {{  // 3字节（中文）
            charCode = ((*p++ & 0x0F) << 12);
            charCode |= ((*p++ & 0x3F) << 6);
            charCode |= (*p++ & 0x3F);
        }} else if ((*p & 0xF8) == 0xF0) {{  // 4字节
            charCode = ((*p++ & 0x07) << 18);
            charCode |= ((*p++ & 0x3F) << 12);
            charCode |= ((*p++ & 0x3F) << 6);
            charCode |= (*p++ & 0x3F);
        }} else {{
            p++;  // 跳过无效字节
            continue;
        }}

        // 绘制字符并移动光标
        draw{OUTPUT_NAME.title().replace('_', '')}Char(display, currentX, y, charCode);
        
        // 根据实际字符宽度移动（查表获取精确宽度）
"""
    
    # 添加字符宽度表
    h_content += "        uint8_t charWidth = 16;  // 默认宽度\n"
    h_content += "        switch(charCode) {\n"
    for info in char_info:
        h_content += f"            case 0x{info['unicode']:04X}: charWidth = {info['width']}; break;\n"
    h_content += "        }\n"
    h_content += "        currentX += charWidth + 1;  // 字符宽度 + 1像素间隔\n"
    h_content += "    }\n"
    h_content += "}\n\n"
    
    h_content += f"#endif // _{OUTPUT_NAME.upper()}_{FONT_SIZE}PT_H_\n"
    
    # 保存文件
    output_path = os.path.join(PROJECT_ROOT, "components", "fonts", f"{OUTPUT_NAME}{FONT_SIZE}pt.h")
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(h_content)
    
    print()
    print(f"✅ 生成成功: {output_path}")
    print()
    print("=" * 60)
    print("使用方法:")
    print("=" * 60)
    print(f"#include \"../fonts/{OUTPUT_NAME}{FONT_SIZE}pt.h\"")
    print(f"draw{OUTPUT_NAME.title().replace('_', '')}String(display, 10, 200, \"{CHARS}\");")
    print("=" * 60)

if __name__ == "__main__":
    generate_bitmap_arrays()
