#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
快速转换 Comic Sans MS Bold 字体
"""

from PIL import Image, ImageDraw, ImageFont
import os

# 配置
TTF_PATH = "components/fonts/仿宋_GB2312.ttf"
CHARS = "测试文字ABC123"
FONT_SIZE = 16
OUTPUT_NAME = "fangsong_chinese"

def generate_gfx_font():
    """生成 GFX 格式字体"""
    
    print(f"🔄 正在转换字体...")
    print(f"📁 字体文件: {TTF_PATH}")
    print(f"📝 字符: {CHARS}")
    print(f"📏 字号: {FONT_SIZE}")
    print()
    
    if not os.path.exists(TTF_PATH):
        print(f"❌ 字体文件不存在: {TTF_PATH}")
        return
    
    try:
        font = ImageFont.truetype(TTF_PATH, FONT_SIZE)
        print("✅ 字体加载成功")
    except Exception as e:
        print(f"❌ 加载字体失败: {e}")
        return
    
    # 按 Unicode 排序（重要！）
    sorted_chars = sorted(set(CHARS), key=lambda c: ord(c))
    
    bitmaps = []
    glyphs = []
    bitmap_offset = 0
    
    # 为每个字符生成位图
    for char in sorted_chars:
        try:
            # 获取字符边界
            bbox = font.getbbox(char)
            width = bbox[2] - bbox[0]
            height = bbox[3] - bbox[1]
            x_offset = bbox[0]
            y_offset = -bbox[3]
            
            if width <= 0 or height <= 0:
                print(f"⚠️  字符 '{char}' (U+{ord(char):04X}) 尺寸为0，跳过")
                continue
            
            # 创建图像
            img = Image.new('1', (width, height), 1)
            draw = ImageDraw.Draw(img)
            draw.text((-bbox[0], -bbox[1]), char, font=font, fill=0)
            
            # 转换为字节数组 (按行扫描，每8个像素一个字节)
            pixels = list(img.getdata())
            bitmap_bytes = []
            
            for y in range(height):
                for x in range(0, width, 8):
                    byte = 0
                    for bit in range(8):
                        if x + bit < width:
                            pixel_index = y * width + x + bit
                            if pixels[pixel_index] == 0:  # 黑色像素
                                byte |= (0x80 >> bit)
                    bitmap_bytes.append(byte)
            
            bitmaps.extend(bitmap_bytes)
            
            # 计算 x_advance (字符宽度 + 间距)
            x_advance = width + 1
            
            # 生成 Glyph 信息
            glyphs.append({
                'char': char,
                'unicode': ord(char),
                'bitmap_offset': bitmap_offset,
                'width': width,
                'height': height,
                'x_advance': x_advance,
                'x_offset': x_offset,
                'y_offset': y_offset,
                'bitmap_size': len(bitmap_bytes)
            })
            
            bitmap_offset += len(bitmap_bytes)
            
            print(f"✓ '{char}' (U+{ord(char):04X}): {width}x{height}, {len(bitmap_bytes)} bytes")
            
        except Exception as e:
            print(f"❌ 处理字符 '{char}' 失败: {e}")
            continue
    
    if len(glyphs) == 0:
        print("❌ 没有成功转换任何字符")
        return
    
    print()
    print(f"✅ 成功转换 {len(glyphs)} 个字符")
    print(f"📊 总位图大小: {len(bitmaps)} bytes")
    print()
    
    # 生成 .h 文件
    first_char = glyphs[0]['unicode']
    last_char = glyphs[-1]['unicode']
    
    h_content = f"""// Font: {OUTPUT_NAME} {FONT_SIZE}pt
// Generated by quick_convert.py
// Characters: {CHARS}
// Character count: {len(glyphs)}
// Bitmap size: {len(bitmaps)} bytes

#ifndef _{OUTPUT_NAME.upper()}_{FONT_SIZE}PT7B_H_
#define _{OUTPUT_NAME.upper()}_{FONT_SIZE}PT7B_H_

#include <Adafruit_GFX.h>

const uint8_t {OUTPUT_NAME}{FONT_SIZE}ptBitmaps[] PROGMEM = {{
"""
    
    # 位图数据
    for i, byte in enumerate(bitmaps):
        if i % 16 == 0:
            h_content += "    "
        h_content += f"0x{byte:02X}"
        if i < len(bitmaps) - 1:
            h_content += ", "
        if (i + 1) % 16 == 0 and i < len(bitmaps) - 1:
            h_content += "\n"
    
    h_content += "\n};\n\n"
    
    # Glyphs 数据
    h_content += f"const GFXglyph {OUTPUT_NAME}{FONT_SIZE}ptGlyphs[] PROGMEM = {{\n"
    
    for g in glyphs:
        h_content += f"    {{ {g['bitmap_offset']:5d}, {g['width']:3d}, {g['height']:3d}, "
        h_content += f"{g['x_advance']:3d}, {g['x_offset']:4d}, {g['y_offset']:4d} }}"
        h_content += f",  // U+{g['unicode']:04X} '{g['char']}'\n"
    
    h_content = h_content.rstrip(',\n') + '\n'  # 移除最后的逗号
    h_content += "};\n\n"
    
    # Font 结构
    h_content += f"""const GFXfont {OUTPUT_NAME}{FONT_SIZE}pt7b PROGMEM = {{
    (uint8_t *){OUTPUT_NAME}{FONT_SIZE}ptBitmaps,
    (GFXglyph *){OUTPUT_NAME}{FONT_SIZE}ptGlyphs,
    0x{first_char:04X}, 0x{last_char:04X}, {FONT_SIZE}
}};

#endif // _{OUTPUT_NAME.upper()}_{FONT_SIZE}PT7B_H_
"""
    
    # 保存文件
    output_path = f"components/fonts/{OUTPUT_NAME}{FONT_SIZE}pt7b.h"
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(h_content)
    
    print(f"✅ 文件已生成: {output_path}")
    print()
    print("=" * 60)
    print("使用方法:")
    print("=" * 60)
    print(f"#include \"../fonts/{OUTPUT_NAME}{FONT_SIZE}pt7b.h\"")
    print(f"display.setFont(&{OUTPUT_NAME}{FONT_SIZE}pt7b);")
    print(f'display.print("{CHARS}");')
    print("=" * 60)

if __name__ == "__main__":
    generate_gfx_font()
